name: py-da-stack
channels:
  - conda-forge
dependencies:
  - python=3.8
  - basemap
  - cartopy
  - cartopy_offlinedata
  - cmocean
  - cmaps
  - dask
  - dask-jobqueue
  - dask-labextension
  - datashader
  - distributed
  - geopandas
  - geoviews
  - gsw
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - intake
  - intake-xarray
  - joblib
  - jupyter-server-proxy
  - jupytext
  - lz4
  - matplotlib-base
  - nbval
  - nbgitpuller
  - netcdf4
  - nomkl
  - numba
  - numcodecs
  - numpy
  - pandas
  - panel
  - papermill
  - pip
  - pyresample
  - pytest
  - python-blosc
  - scipy
  - seaborn
  - seawater
  - shapely
  - xarray
  - xgcm
  - xhistogram
  - xpublish
  - zarr
